- name: Executing Remote SSH Commands
        uses: appleboy/ssh-action@master
        with:
          host: 103.93.135.75
          username: ubuntu
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/ubuntu/uas-project
            sudo docker-compose down --volumes --remove-orphans
            sudo docker stop uas-web-container || true
            sudo docker rm -f uas-web-container || true
            sudo docker-compose up -d --build --force-recreate
